// Copyright 2026 NVIDIA CORPORATION & AFFILIATES.
//
// SPDX-License-Identifier: Apache-2.0

// Command configgen converts the repository-root cluster-config.yaml into a
// Go byte slice that can be embedded in binaries built outside the source tree.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	input := flag.String("input", "", "path to the canonical YAML defaults")
	output := flag.String("output", "", "path to the generated Go source")
	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "both -input and -output are required")
		os.Exit(2)
	}

	data, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read defaults: %v\n", err)
		os.Exit(1)
	}

	var literal strings.Builder
	literal.WriteString("var defaultConfigYAML = []byte(\n")
	for _, line := range strings.SplitAfter(string(data), "\n") {
		if line == "" {
			continue
		}
		literal.WriteString("\t")
		literal.WriteString(strconv.Quote(line))
		literal.WriteString(" +\n")
	}
	literal.WriteString("\t\"\",\n)\n")

	source := "// Copyright 2026 NVIDIA CORPORATION & AFFILIATES.\n" +
		"//\n" +
		"// SPDX-License-Identifier: Apache-2.0\n\n" +
		"// Code generated by go generate; DO NOT EDIT.\n\n" +
		"package config\n\n" +
		literal.String()

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create output directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, []byte(source), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated source: %v\n", err)
		os.Exit(1)
	}
}
