apiVersion: configuration.net.nvidia.com/v1alpha1
kind: NicConfigurationTemplate
metadata:
  name: spectrum-x-configuration{{suffix .ClusterConfig.Identifier}}
  namespace: "{{.NetworkOperator.Namespace}}"
spec:
  {{- if .ClusterConfig.NodeSelector }}
  nodeSelector:
    {{- range $key, $value := .ClusterConfig.NodeSelector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  nicSelector:
    nicType: "{{spectrumXNicType .ClusterConfig}}"
    pciAddresses: [{{- $first := true }}{{- range $addr := spectrumXPCIAddresses .ClusterConfig }}{{- if not $first }}, {{ end }}{{- $first = false }}"{{$addr}}"{{- end }}]
  template:
    numVfs: 1
    linkType: Ethernet
    spectrumXOptimized:
      enabled: true
      version: "{{.Profile.SpectrumX.SPCXVersion}}"
      multiplaneMode: "{{.Profile.SpectrumX.MultiplaneMode}}"  # none, swplb, hwplb
      numberOfPlanes: {{.Profile.SpectrumX.NumberOfPlanes}}
      overlay: "{{.SpectrumX.Overlay}}"
