// Copyright 2025 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/nvidia/k8s-launch-kit/pkg/config"
	apperrors "github.com/nvidia/k8s-launch-kit/pkg/errors"
	"github.com/nvidia/k8s-launch-kit/pkg/kubeclient"
	"github.com/nvidia/k8s-launch-kit/pkg/networkoperatorplugin"
	"github.com/nvidia/k8s-launch-kit/pkg/networkoperatorplugin/connectivity"
	"github.com/nvidia/k8s-launch-kit/pkg/options"
	"github.com/nvidia/k8s-launch-kit/pkg/ui"
)

var (
	deploymentFiles string
	// deployTimeout caps the entire `l8k deploy` invocation. Zero (the
	// default) means no deadline — the apply state machine polls
	// until every manifest reaches a terminal state or the user
	// cancels.
	deployTimeout time.Duration
	// deployTestConnectivity chains the data-plane connectivity
	// matrix (the same one `l8k validate --connectivity` runs)
	// right after a successful deploy. Off by default; opt-in for
	// pipelines that want end-to-end verification in one command.
	deployTestConnectivity bool
	// overwriteExistingFlag promotes Phase 0 helm install to
	// `helm upgrade --install` when a release already exists with
	// values that differ from the rendered values.yaml. Off by default
	// so accidental re-runs don't clobber a user's hand-tuned install.
	overwriteExistingFlag bool
)

// DefaultDeploymentDir is the default directory `l8k generate` writes
// manifests to and `l8k deploy` reads from when --deployment-files is
// not specified.
const DefaultDeploymentDir = "./deployment"

// networkOperatorManifestSubdir is the subdirectory `l8k generate` nests
// network-operator manifests under (matches l.options.SaveDeploymentFiles +
// profile.Plugin in pkg/app/deploy.go).
const networkOperatorManifestSubdir = "network-operator"

var deployCmd = &cobra.Command{
	Use:   "deploy",
	Short: "Apply previously generated manifests to a Kubernetes cluster",
	Long: `Apply Kubernetes manifests previously generated by 'l8k generate' to a cluster.

The command reads YAML files from --deployment-files (default ./deployment)
and applies them in four phases:

  1. NicClusterPolicy   — apply, wait until ready (upstream of everything)
  2. NicNodePolicies    — apply each + wait per policy (per-node gating)
  3. Remaining manifests — apply ALL in one pass (networks, IP pools,
     SR-IOV/Spectrum-X policies, example workloads). Controllers
     reconcile concurrently, so we don't serialize on each.
  4. Verify             — poll each manifest applied in phase 3 until it
     reaches a terminal state (success/error).

Use --deploy-timeout to bound the entire end-to-end run (e.g. for a
maintenance window). Without the flag the deploy waits indefinitely for
reconciliation — appropriate for large SR-IOV clusters where a single
policy can take an hour or more.

If <deployment-files>/network-operator/ exists (the layout 'l8k generate'
produces), that subdirectory is used. Otherwise <deployment-files> itself
is used as the manifest directory.`,
	Example: `  # Apply manifests from ./deployment to the cluster reachable via $KUBECONFIG
  l8k deploy

  # Custom directory and explicit kubeconfig
  l8k deploy --deployment-files /tmp/my-output --kubeconfig ~/.kube/config

  # Server-side dry run: validate against the cluster without persisting
  l8k deploy --dry-run`,
	Run: func(cmd *cobra.Command, args []string) {
		resolved, err := resolveKubeconfig(kubeconfig)
		if err != nil {
			exitWithError(apperrors.NewValidationError(
				"kubeconfig required for deploy",
				err,
				"Set $KUBECONFIG or pass --kubeconfig <path>",
			), outputFormat)
		}

		manifestDir, err := resolveDeploymentDir(deploymentFiles)
		if err != nil {
			exitWithError(apperrors.NewValidationError(
				"deployment files directory not found",
				err,
				"Run 'l8k generate' first or pass --deployment-files <path>",
			), outputFormat)
		}

		log.Log.Info("Deploying manifests", "kubeconfig", resolved, "manifestDir", manifestDir, "dryRun", dryRunFlag)

		k8sClient, restConfig, err := kubeclient.New(resolved)
		if err != nil {
			exitWithError(apperrors.NewClusterError(
				"failed to create Kubernetes client",
				err,
				"Check that kubeconfig is valid and the cluster is reachable",
			), outputFormat)
		}

		uiOutput, _ := ui.NewOutputForFormat(outputFormat, yesFlag)
		ctx := ui.WithOutput(context.Background(), uiOutput)
		if deployTimeout > 0 {
			var cancel context.CancelFunc
			ctx, cancel = context.WithTimeout(ctx, deployTimeout)
			defer cancel()
		}

		if dryRunFlag {
			uiOutput.Section("Dry Run: Cluster Deployment (preview)")
			uiOutput.Info("Manifests in %s will be sent to the cluster with server-side dry-run.", manifestDir)
		} else {
			uiOutput.Section("Cluster Deployment")
			uiOutput.Info("Applying manifests from %s", manifestDir)
		}

		// Load cluster-config.yaml when present (auto-discovered next
		// to --deployment-files or in CWD) so Phase 0 helm install and
		// the Phase 0.5 preflight checks have catalog-resolved chart
		// version, helm repo URL, operator namespace, and component /
		// DOCA versions to compare against. Without this, every check
		// soft-skips with "no expected version" — useless.
		deployOpts := networkoperatorplugin.DeployOptions{
			DryRun:            dryRunFlag,
			OverwriteExisting: overwriteExistingFlag,
			RestConfig:        restConfig,
		}
		cfg, cfgPath, cfgErr := loadUserConfig(options.Options{})
		if cfgErr != nil {
			exitWithError(apperrors.NewValidationError(
				"failed to load user config",
				cfgErr,
				"Verify the YAML is parseable and networkOperator.selectedRelease is set to a supported MAJOR.MINOR (e.g. 26.4), or re-run `l8k discover`",
			), outputFormat)
		}
		if cfg != nil {
			deployOpts.NetworkOperator = cfg.NetworkOperator
			if cfg.DOCADriver != nil {
				deployOpts.DOCAVersion = cfg.DOCADriver.Version
			}
			log.Log.V(1).Info("Loaded user config for deploy",
				"path", cfgPath,
				"selectedRelease", selectedReleaseFromCfg(cfg))
		}
		if err := networkoperatorplugin.ApplyManifestsFromDir(ctx, k8sClient, manifestDir, deployOpts); err != nil {
			// Pass StructuredError through as-is — the deploy
			// internals build them with actionable Message +
			// Suggestion text. Re-wrapping would clobber the
			// suggestion and duplicate the message.
			var se *apperrors.StructuredError
			if errors.As(err, &se) {
				exitWithError(se, outputFormat)
			}
			exitWithError(apperrors.NewDeploymentError(
				"deployment failed",
				err,
				"Check cluster connectivity, RBAC, and manifest validity.",
			), outputFormat)
		}

		if dryRunFlag {
			uiOutput.Success("Dry run completed — no changes were applied")
		} else {
			uiOutput.Success("Deployment completed")
		}

		if deployTestConnectivity && !dryRunFlag {
			// Pipeline the connectivity matrix straight after a
			// successful apply. We deliberately do NOT re-run the
			// version check here — deploy just landed manifests
			// from this binary's catalog, the version is whatever
			// we shipped. Connectivity is the value-add.
			matrix, err := connectivity.RunMatrix(ctx, k8sClient, restConfig, uiOutput, connectivity.Options{
				ManifestDir: manifestDir,
				Timeout:     0, // RunMatrix defaults to 5m
			})
			if err != nil {
				exitWithError(apperrors.NewClusterError(
					"deploy succeeded but --test-connectivity failed",
					err,
					"Inspect the test DaemonSet via --keep + kubectl get pods",
				), outputFormat)
			}
			if matrix != nil && matrix.Summary.Failed > 0 {
				exitWithError(apperrors.NewDeploymentError(
					fmt.Sprintf("connectivity matrix failed: %d/%d passed", matrix.Summary.Passed, matrix.Summary.TotalTests),
					nil,
					"Examine the failures above; re-run with --keep to keep the test DaemonSet for debugging",
				), outputFormat)
			}
		}
	},
}

// resolveDeploymentDir prefers <dir>/network-operator/ when present (matches
// the layout 'l8k generate' produces), falling back to <dir> itself.
// Returns an error if neither path exists or is not a directory.
func resolveDeploymentDir(dir string) (string, error) {
	if dir == "" {
		dir = DefaultDeploymentDir
	}
	candidate := filepath.Join(dir, networkOperatorManifestSubdir)
	if info, err := os.Stat(candidate); err == nil && info.IsDir() {
		return candidate, nil
	}
	if info, err := os.Stat(dir); err == nil && info.IsDir() {
		return dir, nil
	}
	return "", fmt.Errorf("not found: %s (also checked %s)", dir, candidate)
}

func init() {
	rootCmd.AddCommand(deployCmd)

	deployCmd.Flags().StringVar(&kubeconfig, "kubeconfig", "", "Path to kubeconfig file (falls back to $KUBECONFIG, then ~/.kube/config)")
	deployCmd.Flags().StringVar(&deploymentFiles, "deployment-files", DefaultDeploymentDir, "Directory containing the manifests to apply")
	deployCmd.Flags().StringVar(&userConfig, "user-config", "", "Cluster config file (auto-discovered from ./cluster-config.yaml or <deployment-files>/../cluster-config.yaml). Used to resolve the network-operator release for Phase 0 helm install and Phase 0.5 preflight checks.")
	deployCmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Preview the deployment via server-side dry-run without persisting changes")
	deployCmd.Flags().DurationVar(&deployTimeout, "deploy-timeout", 0, "Maximum end-to-end wall-clock budget for the deploy phase (e.g. 45m, 2h). 0 (the default) means no deadline; the deploy polls until every manifest reaches a terminal state. Useful for matching a maintenance window when SR-IOV reconciliation on a large cluster can take an hour or more.")
	deployCmd.Flags().BoolVar(&deployTestConnectivity, "test-connectivity", false, "After a successful deploy, run the connectivity matrix (apply example DaemonSet → wait Ready → RDMA matrix → cleanup) to verify the data plane end-to-end.")
	deployCmd.Flags().BoolVar(&overwriteExistingFlag, "overwrite-existing", false, "Converge the cluster to the rendered manifests when preflight detects drift: helm upgrade the chart on chart-version/values mismatch, delete stray Network Operator CRs in the operator namespace, and rewrite NicClusterPolicy component versions via SSA. Off by default — preflight fails fast and lists what would change.")

	setFlagGroup(deployCmd, "kubeconfig", GroupCommon)
	setFlagGroup(deployCmd, "deployment-files", GroupGeneration)
	setFlagGroup(deployCmd, "deploy-timeout", GroupDeploy)
	setFlagGroup(deployCmd, "dry-run", GroupDeploy)
	setFlagGroup(deployCmd, "test-connectivity", GroupDeploy)
	setFlagGroup(deployCmd, "overwrite-existing", GroupDeploy)
}

// selectedReleaseFromCfg returns the catalog key the user-config pinned, or
// "" when the file didn't carry a networkOperator block.
func selectedReleaseFromCfg(cfg *config.LaunchKitConfig) string {
	if cfg == nil || cfg.NetworkOperator == nil {
		return ""
	}
	return cfg.NetworkOperator.SelectedRelease
}
