// Copyright 2025 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"time"

	"github.com/spf13/cobra"

	"github.com/nvidia/k8s-launch-kit/pkg/target"
	hosttarget "github.com/nvidia/k8s-launch-kit/pkg/target/host"
)

var (
	deploymentFiles string
	// deployTimeout caps the entire `l8k deploy` invocation. Zero (the
	// default) means no deadline — the apply state machine polls
	// until every manifest reaches a terminal state or the user
	// cancels.
	deployTimeout time.Duration
	// overwriteExistingFlag promotes Phase 0 helm install to
	// `helm upgrade --install` when a release already exists with
	// values that differ from the rendered values.yaml. Off by default
	// so accidental re-runs don't clobber a user's hand-tuned install.
	overwriteExistingFlag bool
)

// DefaultDeploymentDir is the default directory `l8k generate` writes
// manifests to and `l8k deploy` reads from when --deployment-files is
// not specified.
const DefaultDeploymentDir = hosttarget.DefaultDeploymentDir

var deployCmd = &cobra.Command{
	Use:   "deploy",
	Short: "Apply previously generated manifests to a Kubernetes cluster",
	Long: `Apply Kubernetes manifests previously generated by 'l8k generate' to a cluster.

The command reads YAML files from --deployment-files (default ./deployment)
and applies them in four phases:

  1. NicClusterPolicy   — apply, wait until ready (upstream of everything)
  2. NicNodePolicies    — apply each + wait per policy (per-node gating)
  3. Remaining manifests — apply ALL in one pass (networks, IP pools,
     SR-IOV/Spectrum-X policies, example workloads). Controllers
     reconcile concurrently, so we don't serialize on each.
  4. Verify             — poll each manifest applied in phase 3 until it
     reaches a terminal state (success/error).

Use --deploy-timeout to bound the entire end-to-end run (e.g. for a
maintenance window). Without the flag the deploy waits indefinitely for
reconciliation — appropriate for large SR-IOV clusters where a single
policy can take an hour or more.

If <deployment-files>/network-operator/ exists (the layout 'l8k generate'
produces), that subdirectory is used. Otherwise <deployment-files> itself
is used as the manifest directory.`,
	Example: `  # Apply manifests from ./deployment to the cluster reachable via $KUBECONFIG
  l8k deploy

  # Custom directory and explicit kubeconfig
  l8k deploy --deployment-files /tmp/my-output --kubeconfig ~/.kube/config

  # Server-side dry run: validate against the cluster without persisting
  l8k deploy --dry-run`,
	Run: func(cmd *cobra.Command, args []string) {
		runTargetCommand(cmd, target.Deploy, hosttarget.NewDeployAdapter(
			hosttarget.DeployRequest{
				LaunchKitVersion:  Version,
				Kubeconfig:        kubeconfig,
				DeploymentFiles:   deploymentFiles,
				UserConfig:        userConfig,
				ConfigDir:         configDir,
				OperatorNamespace: networkOperatorNamespace,
				OverwriteExisting: overwriteExistingFlag,
			},
			hosttarget.NewDeployRunner(),
		))
	},
}

func init() {
	rootCmd.AddCommand(deployCmd)
	addTargetFlag(deployCmd)

	deployCmd.Flags().StringVar(&kubeconfig, "kubeconfig", "", "Path to kubeconfig file (falls back to $KUBECONFIG, then ~/.kube/config)")
	deployCmd.Flags().StringVar(&deploymentFiles, "deployment-files", DefaultDeploymentDir, "Directory containing the manifests to apply")
	// --network-operator-namespace overrides cfg.NetworkOperator.Namespace in
	// the Host deploy service. It drives the Phase 0 Helm target, Phase 0.5
	// preflight scope, and downstream options that read the namespace.
	deployCmd.Flags().StringVar(&networkOperatorNamespace, "network-operator-namespace", "", "Override the network operator namespace from cluster-config.yaml")
	deployCmd.Flags().StringVar(&userConfig, "user-config", "", "Cluster config file (auto-discovered from ./cluster-config.yaml or <deployment-files>/../cluster-config.yaml). Used to resolve the network-operator release for Phase 0 helm install and Phase 0.5 preflight checks.")
	deployCmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Preview the deployment via server-side dry-run without persisting changes")
	deployCmd.Flags().DurationVar(&deployTimeout, "deploy-timeout", 0, "Maximum end-to-end wall-clock budget for the deploy phase (e.g. 45m, 2h). 0 (the default) means no deadline; the deploy polls until every manifest reaches a terminal state. Useful for matching a maintenance window when SR-IOV reconciliation on a large cluster can take an hour or more.")
	deployCmd.Flags().BoolVar(&overwriteExistingFlag, "overwrite-existing", false, "Converge the cluster to the rendered manifests when preflight detects drift: helm upgrade the chart on chart-version/values mismatch, delete stray Network Operator CRs in the operator namespace, and rewrite NicClusterPolicy component versions via SSA. Off by default — preflight fails fast and lists what would change.")

	setFlagGroup(deployCmd, "kubeconfig", GroupCommon)
	setFlagGroup(deployCmd, "user-config", GroupCommon)
	setFlagGroup(deployCmd, "deployment-files", GroupGeneration)
	setFlagGroup(deployCmd, "network-operator-namespace", GroupCommon)
	setFlagGroup(deployCmd, "deploy-timeout", GroupExecution)
	setFlagGroup(deployCmd, "dry-run", GroupExecution)
	setFlagGroup(deployCmd, "overwrite-existing", GroupDeploy)
	markDeployTargetScopes()
}
