// Copyright 2025 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"sigs.k8s.io/controller-runtime/pkg/log"

	apperrors "github.com/nvidia/k8s-launch-kit/pkg/errors"
	"github.com/nvidia/k8s-launch-kit/pkg/kubeclient"
	"github.com/nvidia/k8s-launch-kit/pkg/networkoperatorplugin"
	"github.com/nvidia/k8s-launch-kit/pkg/ui"
)

var deploymentFiles string

// DefaultDeploymentDir is the default directory `l8k generate` writes
// manifests to and `l8k deploy` reads from when --deployment-files is
// not specified.
const DefaultDeploymentDir = "./deployment"

// networkOperatorManifestSubdir is the subdirectory `l8k generate` nests
// network-operator manifests under (matches l.options.SaveDeploymentFiles +
// profile.Plugin in pkg/app/deploy.go).
const networkOperatorManifestSubdir = "network-operator"

var deployCmd = &cobra.Command{
	Use:   "deploy",
	Short: "Apply previously generated manifests to a Kubernetes cluster",
	Long: `Apply Kubernetes manifests previously generated by 'l8k generate' to a cluster.

The command reads YAML files from --deployment-files (default ./deployment)
and applies them in dependency order: NicClusterPolicy first (waits ready),
then per-group NicNodePolicy (waits ready each), then remaining manifests
(networks, IP pools, example workloads).

If <deployment-files>/network-operator/ exists (the layout 'l8k generate'
produces), that subdirectory is used. Otherwise <deployment-files> itself
is used as the manifest directory.`,
	Example: `  # Apply manifests from ./deployment to the cluster reachable via $KUBECONFIG
  l8k deploy

  # Custom directory and explicit kubeconfig
  l8k deploy --deployment-files /tmp/my-output --kubeconfig ~/.kube/config

  # Server-side dry run: validate against the cluster without persisting
  l8k deploy --dry-run`,
	Run: func(cmd *cobra.Command, args []string) {
		resolved, err := resolveKubeconfig(kubeconfig)
		if err != nil {
			exitWithError(apperrors.NewValidationError(
				"kubeconfig required for deploy",
				err,
				"Set $KUBECONFIG or pass --kubeconfig <path>",
			), outputFormat)
		}

		manifestDir, err := resolveDeploymentDir(deploymentFiles)
		if err != nil {
			exitWithError(apperrors.NewValidationError(
				"deployment files directory not found",
				err,
				"Run 'l8k generate' first or pass --deployment-files <path>",
			), outputFormat)
		}

		log.Log.Info("Deploying manifests", "kubeconfig", resolved, "manifestDir", manifestDir, "dryRun", dryRunFlag)

		k8sClient, _, err := kubeclient.New(resolved)
		if err != nil {
			exitWithError(apperrors.NewClusterError(
				"failed to create Kubernetes client",
				err,
				"Check that kubeconfig is valid and the cluster is reachable",
			), outputFormat)
		}

		uiOutput, _ := ui.NewOutputForFormat(outputFormat, yesFlag)
		ctx := ui.WithOutput(context.Background(), uiOutput)

		if dryRunFlag {
			uiOutput.Section("Dry Run: Cluster Deployment (preview)")
			uiOutput.Info("Manifests in %s will be sent to the cluster with server-side dry-run.", manifestDir)
		} else {
			uiOutput.Section("Cluster Deployment")
			uiOutput.Info("Applying manifests from %s", manifestDir)
		}

		if err := networkoperatorplugin.ApplyManifestsFromDir(ctx, k8sClient, manifestDir, dryRunFlag); err != nil {
			exitWithError(apperrors.NewDeploymentError(
				"deployment failed",
				err,
				"Check cluster connectivity, RBAC, and manifest validity",
			), outputFormat)
		}

		if dryRunFlag {
			uiOutput.Success("Dry run completed — no changes were applied")
		} else {
			uiOutput.Success("Deployment completed")
		}
	},
}

// resolveDeploymentDir prefers <dir>/network-operator/ when present (matches
// the layout 'l8k generate' produces), falling back to <dir> itself.
// Returns an error if neither path exists or is not a directory.
func resolveDeploymentDir(dir string) (string, error) {
	if dir == "" {
		dir = DefaultDeploymentDir
	}
	candidate := filepath.Join(dir, networkOperatorManifestSubdir)
	if info, err := os.Stat(candidate); err == nil && info.IsDir() {
		return candidate, nil
	}
	if info, err := os.Stat(dir); err == nil && info.IsDir() {
		return dir, nil
	}
	return "", fmt.Errorf("not found: %s (also checked %s)", dir, candidate)
}

func init() {
	rootCmd.AddCommand(deployCmd)

	deployCmd.Flags().StringVar(&kubeconfig, "kubeconfig", "", "Path to kubeconfig file (falls back to $KUBECONFIG)")
	deployCmd.Flags().StringVar(&deploymentFiles, "deployment-files", DefaultDeploymentDir, "Directory containing the manifests to apply")
	deployCmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Preview the deployment via server-side dry-run without persisting changes")

	setFlagGroup(deployCmd, "kubeconfig", GroupCommon)
	setFlagGroup(deployCmd, "deployment-files", GroupGeneration)
}
