// Copyright 2025 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/nvidia/k8s-launch-kit/pkg/app"
	apperrors "github.com/nvidia/k8s-launch-kit/pkg/errors"
	applog "github.com/nvidia/k8s-launch-kit/pkg/log"
	"github.com/nvidia/k8s-launch-kit/pkg/networkoperatorplugin"
	"github.com/nvidia/k8s-launch-kit/pkg/options"
	"github.com/nvidia/k8s-launch-kit/pkg/ui"
)

var (
	logLevel              string
	logFile               string
	fabric                string
	deploymentType        string
	multirail             bool
	spectrumX             bool
	ai                    bool
	spcxVersion           string
	multiplaneMode        string
	numberOfPlanes        int
	prompt                string
	llmApiKey             string
	llmApiUrl             string
	llmVendor             string
	llmModel              string
	llmInteractive        bool
	saveDeploymentFiles   string
	deploy                bool
	kubeconfig            string
	userConfig            string
	discoverClusterConfig bool
	saveClusterConfig     string
	logger                = log.Log.WithName("l8k")
	enableDocaDriver            bool
	enabledPlugins              string
	networkOperatorNamespace    string
	group                       string
	labelSelector               string
	podNamespace                string
	sosreportPath               string
	llmThrottle                 bool
	outputFormat                string
	yesFlag                     bool
	quietFlag                   bool
	dryRunFlag                  bool
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "l8k",
	Short: "NVIDIA Kubernetes Launch Kit",
	Long: `
K8s Launch Kit (l8k) is a CLI tool for deploying and managing NVIDIA cloud-native solutions on Kubernetes. The tool helps provide flexible deployment workflows for optimal network performance with SR-IOV, RDMA, and other networking technologies.

### Discover Cluster Configuration
Deploy a minimal Network Operator profile to automatically discover your cluster's
network capabilities and hardware configuration by using --discover-cluster-config.
This phase can be skipped if you provide your own configuration file by using --user-config.
This phase requires --kubeconfig to be specified.

### Generate Deployment Files
Based on the discovered or provided configuration, 
generate a complete set of YAML deployment files for the selected network profile. 
Files can be saved to disk using --save-deployment-files.
The profile can be defined manually with --fabric, --deployment-type and --multirail flags,
OR generated by an LLM-assisted profile generator with --prompt (requires --llm-api-key and --llm-vendor).

### Deploy to Cluster
Apply the generated deployment files to your Kubernetes cluster by using --deploy. This phase requires --kubeconfig and can be skipped if --deploy is not specified.

### AI Agent / Automation Support
Use --output json for structured machine-readable output (single JSON object to stdout).
Use --yes to auto-confirm prompts, --quiet to suppress informational output, and --dry-run to preview deployments.
Use 'l8k schema' to discover tool capabilities programmatically.`,
	Example: `  # Discover cluster and generate SR-IOV ethernet deployment
  l8k --kubeconfig ~/.kube/config --discover-cluster-config \
    --fabric ethernet --deployment-type sriov --save-deployment-files ./output

  # Generate from saved config (no cluster access needed)
  l8k --user-config cluster-config.yaml --fabric ethernet \
    --deployment-type sriov --save-deployment-files ./output

  # Discover + deploy Spectrum-X with JSON output for automation
  l8k --kubeconfig ~/.kube/config --discover-cluster-config \
    --spectrum-x --spcx-version RA2.1 --deploy --output json --yes

  # Dry-run: preview what would be deployed
  l8k --user-config cluster-config.yaml --spectrum-x --deploy \
    --dry-run --output json

  # Get tool capabilities as JSON (for AI agents)
  l8k schema`,
	Run: func(cmd *cobra.Command, args []string) {
		enabledPlugins := parseEnabledPlugins(enabledPlugins)
		// Create application options from CLI flags
		opts := options.Options{
			LogLevel:              logLevel,
			LogFile:               logFile,
			UserConfig:            userConfig,
			DiscoverClusterConfig: discoverClusterConfig,
			Fabric:                fabric,
			DeploymentType:        deploymentType,
			Multirail:             multirail,
			SpectrumX:             spectrumX,
			Ai:                    ai,
			SPCXVersion:           spcxVersion,
			MultiplaneMode:        multiplaneMode,
			NumberOfPlanes:        numberOfPlanes,
			Prompt:                prompt,
			Group:                group,
			LabelSelector:        labelSelector,
			PodNamespace:         podNamespace,
			SaveDeploymentFiles:   saveDeploymentFiles,
			Deploy:                deploy,
			Kubeconfig:            kubeconfig,
			SaveClusterConfig:        saveClusterConfig,
			NetworkOperatorNamespace: networkOperatorNamespace,
			EnabledPlugins:           enabledPlugins,
			LLMApiKey:             llmApiKey,
			LLMApiUrl:             llmApiUrl,
			LLMVendor:             llmVendor,
			LLMModel:              llmModel,
			LLMInteractive:        llmInteractive,
			SosreportPath:         sosreportPath,
			LLMThrottle:           llmThrottle,
			OutputFormat:           outputFormat,
			Yes:                    yesFlag,
			Quiet:                  quietFlag,
			DryRun:                 dryRunFlag,
		}

		// Set EnableDocaDriver only if the flag was explicitly provided
		if cmd.Flags().Lookup("enable-doca-driver").Changed {
			opts.EnableDocaDriver = &enableDocaDriver
		}

		// Apply Spectrum-X implied defaults (fabric, deployment, multirail)
		if err := applySpectrumXDefaults(&opts); err != nil {
			exitWithError(apperrors.NewValidationError(err.Error(), err, "Check --spectrum-x flag combinations"), opts.OutputFormat)
		}

		// Validate CLI configuration
		if err := validateConfig(&opts); err != nil {
			exitWithError(apperrors.NewValidationError(err.Error(), err, "Run 'l8k --help' for usage information"), opts.OutputFormat)
		}

		logger.Info("SaveConfig", "val", opts)

		// Create and run the application
		launcher := app.New(opts)
		if err := launcher.Run(); err != nil {
			var se *apperrors.StructuredError
			if !errors.As(err, &se) {
				se = apperrors.NewGeneralError(err.Error(), err)
			}
			exitWithError(se, opts.OutputFormat)
		}
	},
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	cobra.OnInitialize(initConfig)

	// Phase 0: Plugin flags
	rootCmd.Flags().StringVar(&enabledPlugins, "enabled-plugins", "network-operator", "Comma-separated list of plugins to enable")

	// Phase 1: Cluster discovery flags
	rootCmd.Flags().BoolVar(&discoverClusterConfig, "discover-cluster-config", false, "Deploy a thin Network Operator profile to discover cluster capabilities")
	rootCmd.Flags().StringVar(&saveClusterConfig, "save-cluster-config", "", "Save discovered cluster configuration to the specified path (defaults to --user-config path if set, otherwise ./cluster-config.yaml)")
	rootCmd.Flags().StringVar(&userConfig, "user-config", "", "Use provided cluster configuration file (as base config for discovery or as full config without discovery)")
	rootCmd.Flags().StringVar(&networkOperatorNamespace, "network-operator-namespace", "", "Override the network operator namespace from the config file")

	// Phase 2: Deployment generation flags
	rootCmd.Flags().StringVar(&fabric, "fabric", "", "Select the fabric type to deploy (infiniband, ethernet)")
	rootCmd.Flags().StringVar(&deploymentType, "deployment-type", "", "Select the deployment type (sriov, rdma_shared, host_device)")
	rootCmd.Flags().BoolVar(&multirail, "multirail", false, "Enable multirail deployment")
	rootCmd.Flags().BoolVar(&spectrumX, "spectrum-x", false, "Enable Spectrum X deployment")
	rootCmd.Flags().BoolVar(&ai, "ai", false, "Enable AI deployment")
	rootCmd.Flags().StringVar(&spcxVersion, "spcx-version", "", "Spectrum-X firmware version (requires --spectrum-x)")
	rootCmd.Flags().StringVar(&multiplaneMode, "multiplane-mode", "", "Spectrum-X multiplane mode: swplb, hwplb, uniplane (requires --spectrum-x)")
	rootCmd.Flags().IntVar(&numberOfPlanes, "number-of-planes", 0, "Number of planes for Spectrum-X (requires --spectrum-x)")
	rootCmd.Flags().StringVar(&group, "group", "", "Generate templates for a specific group only (e.g., group-0)")
	rootCmd.Flags().StringVar(&labelSelector, "label-selector", "feature.node.kubernetes.io/pci-15b3.present=true", "Filter nodes for discovery by label (e.g., key=value,key2=value2)")
	rootCmd.Flags().StringVar(&prompt, "prompt", "", "Path to file with a prompt to use for LLM-assisted profile generation")
	rootCmd.Flags().StringVar(&llmApiKey, "llm-api-key", "", "API key for the LLM API (required when using --prompt)")
	rootCmd.Flags().StringVar(&llmApiUrl, "llm-api-url", "", "API URL for the LLM API")
	rootCmd.Flags().StringVar(&llmVendor, "llm-vendor", "openai-azure", "Vendor of the LLM API: openai, openai-azure, anthropic, gemini")
	rootCmd.Flags().StringVar(&llmModel, "llm-model", "", "Model name for the LLM API (e.g., claude-3-5-sonnet-20241022, gpt-4)")
	rootCmd.Flags().BoolVar(&llmInteractive, "llm-interactive", false, "Enable interactive chat mode for LLM-assisted profile selection")
	rootCmd.Flags().StringVar(&saveDeploymentFiles, "save-deployment-files", "./deployment", "Save generated deployment files to the specified directory")
	rootCmd.Flags().StringVar(&podNamespace, "pod-namespace", "", "Namespace for pods and network resources (overrides config podNamespace, default: 'default')")
	rootCmd.Flags().BoolVar(&enableDocaDriver, "enable-doca-driver", false, "Enable DOCA driver deployment (overrides config file docaDriver.enable)")
	rootCmd.Flags().StringVar(&sosreportPath, "sosreport-path", "", "Path to pre-collected sosreport directory for troubleshooting analysis (implies --llm-interactive)")
	rootCmd.Flags().BoolVar(&llmThrottle, "llm-throttle", false, "Enable rate limit throttling for LLM API calls (use when hitting token-per-minute limits)")

	// Phase 3: Cluster deployment flags
	rootCmd.Flags().BoolVar(&deploy, "deploy", false, "Deploy the generated files to the Kubernetes cluster")
	rootCmd.Flags().StringVar(&kubeconfig, "kubeconfig", "", "Path to kubeconfig file for cluster deployment (required when using --deploy)")

	// Output control flags
	rootCmd.PersistentFlags().StringVar(&outputFormat, "output", "text", "Output format: text (default, human-readable) or json (structured, for automation and AI agents)")
	rootCmd.Flags().BoolVarP(&yesFlag, "yes", "y", false, "Auto-confirm all prompts without interactive input")
	rootCmd.Flags().BoolVarP(&quietFlag, "quiet", "q", false, "Suppress informational output (errors still shown)")
	rootCmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Preview what would be deployed without applying changes to the cluster")

	// Logging flags
	rootCmd.PersistentFlags().StringVar(&logLevel, "log-level", "", "Enable logging at specified level (debug, info, warn, error)")
	rootCmd.PersistentFlags().StringVar(&logFile, "log-file", "", "Write logs to file instead of stderr")
}

// validateConfig validates the CLI flag combinations
func validateConfig(options *options.Options) error {
	// Validate --output flag
	if !slices.Contains([]string{"text", "json"}, options.OutputFormat) {
		return fmt.Errorf("--output must be one of: text, json")
	}

	// Validate --dry-run requires --deploy
	if options.DryRun && !options.Deploy {
		return fmt.Errorf("--dry-run requires --deploy to be specified (it previews what deploy would do)")
	}

	// At least one plugin should be enabled
	if len(options.EnabledPlugins) == 0 {
		return fmt.Errorf("no plugins enabled, use --enabled-plugins to enable plugins")
	}

	// At least one of user-config or discover-cluster-config should be provided
	// (not required in interactive mode — the agent can troubleshoot without a cluster config)
	if options.UserConfig == "" && !options.DiscoverClusterConfig && !options.LLMInteractive {
		return fmt.Errorf("either --user-config or --discover-cluster-config must be provided")
	}

	// Sosreport flags require interactive mode
	if options.SosreportPath != "" && !options.LLMInteractive {
		return fmt.Errorf("--sosreport-path requires --llm-interactive")
	}

	// Resolve kubeconfig from flag or $KUBECONFIG env var for cluster operations
	if options.DiscoverClusterConfig || options.Deploy {
		resolved, err := resolveKubeconfig(options.Kubeconfig)
		if err != nil {
			return fmt.Errorf("kubeconfig required for cluster operations: set $KUBECONFIG or pass --kubeconfig <path>")
		}
		options.Kubeconfig = resolved
	}

	// Spectrum-X specific parameter validation
	if options.SPCXVersion != "" && !options.SpectrumX {
		return fmt.Errorf("--spcx-version can only be used with --spectrum-x")
	}
	if options.MultiplaneMode != "" && !options.SpectrumX {
		return fmt.Errorf("--multiplane-mode can only be used with --spectrum-x")
	}
	if options.NumberOfPlanes != 0 && !options.SpectrumX {
		return fmt.Errorf("--number-of-planes can only be used with --spectrum-x")
	}

	// Network Operator plugin rules
	if slices.Contains(options.EnabledPlugins, networkoperatorplugin.PluginName) {
		// If profile is selected, either save-deployment-files or deploy options should be provided
		if (options.Fabric != "" || options.DeploymentType != "" || options.Prompt != "" || options.LLMInteractive) && options.SaveDeploymentFiles == "" && !options.Deploy {
			return fmt.Errorf("when --deployment-type, --prompt, or --llm-interactive is specified, either --save-deployment-files or --deploy must be provided")
		}

		// Save-deployment-files or deploy can't work without profile
		if options.Fabric == "" && options.DeploymentType == "" && options.Prompt == "" && !options.LLMInteractive && options.UserConfig == "" && options.Deploy {
			return fmt.Errorf("--deploy requires --deployment-type, --prompt, --llm-interactive, or --user-config with a profile to be specified")
		}

		if (options.Prompt != "" || options.LLMInteractive) && (options.Fabric != "" || options.DeploymentType != "") {
			return fmt.Errorf("--fabric and --prompt/--llm-interactive cannot be used together")
		}

		if options.Prompt != "" && options.LLMInteractive {
			return fmt.Errorf("--prompt and --llm-interactive cannot be used together")
		}

		if (options.DeploymentType != "" && options.Fabric == "") || (options.Fabric != "" && options.DeploymentType == "") {
			return fmt.Errorf("--deployment-type requires --fabric to be specified")
		}

		if options.Fabric != "" && !slices.Contains([]string{"infiniband", "ethernet"}, options.Fabric) {
			return fmt.Errorf("--fabric must be one of: infiniband, ethernet")
		}

		if options.DeploymentType != "" && !slices.Contains([]string{"sriov", "rdma_shared", "host_device"}, options.DeploymentType) {
			return fmt.Errorf("--deployment-type must be one of: sriov, rdma_shared, host_device")
		}
	}

	// LLM options validation
	if options.Prompt != "" || options.LLMInteractive {
		if options.LLMApiKey == "" || options.LLMVendor == "" {
			return fmt.Errorf("--prompt or --llm-interactive requires --llm-api-key and --llm-vendor to be specified")
		}

		if !slices.Contains([]string{"openai", "openai-azure", "anthropic", "gemini"}, options.LLMVendor) {
			return fmt.Errorf("--llm-vendor must be one of: openai, openai-azure, anthropic, gemini")
		}
	}

	return nil
}

// applySpectrumXDefaults sets implied defaults when --spectrum-x is used.
// Spectrum-X always requires ethernet fabric, sriov deployment, and multirail.
func applySpectrumXDefaults(opts *options.Options) error {
	if !opts.SpectrumX {
		return nil
	}
	if opts.Fabric != "" && opts.Fabric != "ethernet" {
		return fmt.Errorf("--spectrum-x requires ethernet fabric, got --fabric %s", opts.Fabric)
	}
	if opts.DeploymentType != "" && opts.DeploymentType != "sriov" {
		return fmt.Errorf("--spectrum-x requires sriov deployment, got --deployment-type %s", opts.DeploymentType)
	}
	opts.Fabric = "ethernet"
	opts.DeploymentType = "sriov"
	opts.Multirail = true
	return nil
}

// exitWithError prints the error and exits with the appropriate code.
// In JSON mode, emits a structured JSON error to stdout.
func exitWithError(se *apperrors.StructuredError, outputFormat string) {
	if outputFormat == "json" {
		errJSON, _ := json.Marshal(se)
		result := ui.JSONResult{
			Success: false,
			Error:   errJSON,
		}
		data, _ := json.MarshalIndent(result, "", "  ")
		fmt.Fprintf(os.Stdout, "%s\n", data)
		fmt.Fprintf(os.Stderr, "Error: %s\n", se.Error())
	} else {
		fmt.Fprintf(os.Stderr, "Error: %s\n", se.Error())
	}
	os.Exit(se.ExitCode)
}

func parseEnabledPlugins(enabledPlugins string) []string {
	return strings.Split(enabledPlugins, ",")
}

// resolveKubeconfig resolves the kubeconfig path from flag or environment.
// Priority: 1) --kubeconfig flag, 2) $KUBECONFIG env var
func resolveKubeconfig(flagValue string) (string, error) {
	if flagValue != "" {
		return flagValue, nil
	}
	if envVal := os.Getenv("KUBECONFIG"); envVal != "" {
		return envVal, nil
	}
	return "", fmt.Errorf("no kubeconfig found: set $KUBECONFIG or pass --kubeconfig <path>")
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	// Detect if --log-level was explicitly set
	logLevelFlag := rootCmd.PersistentFlags().Lookup("log-level")
	loggingEnabled := logLevelFlag.Changed

	if loggingEnabled {
		applog.SetLoggingEnabled(true)
		if logLevel == "" {
			logLevel = "info" // default when enabled
		}
	} else {
		applog.SetLoggingEnabled(false)
	}

	// Configure log file if specified
	if logFile != "" {
		if err := applog.SetLogFile(logFile); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: Failed to open log file: %v\n", err)
		}
	}

	// Initialize logging
	applog.InitLog()

	// Set log level if logging is enabled
	if loggingEnabled && logLevel != "" {
		if err := applog.SetLogLevel(logLevel); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: Invalid log level %q: %v\n", logLevel, err)
		}
	}

	// Implementation for config initialization
	// This can be expanded later to read from config files
}
