// Copyright 2026 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package connectivity

import (
	"fmt"
	"sort"
)

// TestPod is one entry in the matrix's source set — a pod with its
// per-rail secondary-network IPs already parsed from the multus
// annotation. Rails are keyed by their multus NetworkAttachmentDefinition
// name (e.g. "rail-0", "rail-1") so the matrix can match same-rail
// endpoints across pods.
type TestPod struct {
	Name      string
	Namespace string
	Node      string
	// IPsByRail is "<rail>" → IPv4 address (first IPv4 only — pods
	// typically have one v4 per attachment). Rails that didn't yield
	// an IP are absent from the map.
	IPsByRail map[string]string
	// RailOrder is the deterministic iteration order over IPsByRail
	// — needed because Go map iteration is randomized and the cross
	// -rail canary picks "rail 0" vs "rail 1" by position.
	RailOrder []string
}

// PingTest is one src→dst test the matrix will execute. Kind tags the
// test bucket: same-rail tests verify the rail is reachable end-to-end;
// cross-rail tests are a single canary per pod pair to spot
// misconfigured routes that would otherwise be invisible if every rail
// passed independently.
//
// SrcPod/DstPod carry the actual k8s pod names — needed by the
// orchestrator to issue the SPDY exec against the right pod. SrcNode/
// DstNode are the kubelet's `Spec.NodeName` for each endpoint and are
// used everywhere the matrix is rendered for humans (operators
// recognize hostnames; DaemonSet-generated pod suffixes are noise).
type PingTest struct {
	Kind    PingTestKind
	SrcPod  string
	DstPod  string
	SrcNode string
	DstNode string
	Rail    string // for same-rail tests; "<srcRail>→<dstRail>" for cross
	SrcIP   string
	DstIP   string
	SrcRail string
	DstRail string
}

// PingTestKind enumerates the buckets the matrix renders into.
type PingTestKind int

const (
	PingSameRail PingTestKind = iota
	PingCrossRail
)

// MatrixSkip captures the soft-skip case where fewer than 2 schedulable
// test pods were found — the matrix returns an empty TestSet plus this
// reason for the operator to see.
type MatrixSkip struct {
	Reason string
}

// MatrixPlan is the full set of tests the orchestrator will execute.
// Generated by Plan() from a sorted list of TestPods so the order is
// deterministic regardless of the cluster's pod-listing order.
type MatrixPlan struct {
	SameRail   []PingTest
	CrossRail  []PingTest
	Skip       *MatrixSkip
}

// Plan builds the test plan from the given pods. The matrix generation
// is pure (no k8s access) so it's straightforward to unit-test against
// fixture pod lists.
//
//   - Same-rail: for every ordered pod pair (A, B) with A≠B, emit one
//     test per rail both endpoints share. This is the data-plane
//     verification proper.
//   - Cross-rail canary: for every ordered pod pair (A, B), emit a
//     single test pinging A.rail[0] → B.rail[1] when both pods have
//     ≥2 rails. Catches routing misconfigurations that allow
//     accidental rail-to-rail leakage (or, when blocked by design,
//     confirms the isolation).
//   - Soft-skip on <2 pods: no tests are emitted and Skip is set so
//     the caller can render "matrix skipped: only N schedulable test
//     pod(s)".
func Plan(pods []TestPod) MatrixPlan {
	if len(pods) < 2 {
		return MatrixPlan{Skip: &MatrixSkip{
			Reason: fmt.Sprintf("only %d schedulable test pod(s) — need ≥2 for a matrix", len(pods)),
		}}
	}

	// Sort pods by name so the plan is stable across runs.
	sorted := make([]TestPod, len(pods))
	copy(sorted, pods)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var plan MatrixPlan
	for i, src := range sorted {
		for j, dst := range sorted {
			if i == j {
				continue
			}
			// Same-rail tests: rails the two endpoints both
			// attach to.
			for _, rail := range src.RailOrder {
				srcIP, ok1 := src.IPsByRail[rail]
				dstIP, ok2 := dst.IPsByRail[rail]
				if !ok1 || !ok2 || srcIP == "" || dstIP == "" {
					continue
				}
				plan.SameRail = append(plan.SameRail, PingTest{
					Kind:    PingSameRail,
					SrcPod:  src.Name,
					DstPod:  dst.Name,
					SrcNode: src.Node,
					DstNode: dst.Node,
					Rail:    rail,
					SrcIP:   srcIP,
					DstIP:   dstIP,
					SrcRail: rail,
					DstRail: rail,
				})
			}
			// Cross-rail canary: src.rail[0] → dst.rail[1] when
			// both pods have ≥2 rails. Skipped otherwise.
			if len(src.RailOrder) >= 2 && len(dst.RailOrder) >= 2 {
				srcRail, dstRail := src.RailOrder[0], dst.RailOrder[1]
				srcIP, ok1 := src.IPsByRail[srcRail]
				dstIP, ok2 := dst.IPsByRail[dstRail]
				if ok1 && ok2 && srcIP != "" && dstIP != "" {
					plan.CrossRail = append(plan.CrossRail, PingTest{
						Kind:    PingCrossRail,
						SrcPod:  src.Name,
						DstPod:  dst.Name,
						SrcNode: src.Node,
						DstNode: dst.Node,
						Rail:    fmt.Sprintf("%s→%s", srcRail, dstRail),
						SrcIP:   srcIP,
						DstIP:   dstIP,
						SrcRail: srcRail,
						DstRail: dstRail,
					})
				}
			}
		}
	}

	return plan
}
