# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class L8k < Formula
  desc "CLI for deploying NVIDIA cloud-native networking on Kubernetes"
  homepage "https://github.com/nvidia/k8s-launch-kit"
  version "26.10.0-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_darwin_amd64.tar.gz"
      sha256 "6b844b22f5c63bb15d9de63d8fce0384d4ed71f4911c08194c71a1e003fe30b7"

      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_darwin_arm64.tar.gz"
      sha256 "ee53a51a5babcf584dc2bacdc41213d7203470dbf2f691b6445eddb01404418a"

      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_linux_amd64.tar.gz"
      sha256 "618946b96b7f89851e56e57daa517beb7444c1874f84e17c91e07fc9bf6ecce8"
      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_linux_arm64.tar.gz"
      sha256 "4cd8662ce6a835ff5fb23b1bbc2814dfed241cf8420325e33b0e8c8ddba49a0f"
      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/l8k version")
    assert_predicate share/"l8k"/"scripts"/"kubectl-netop_sosreport", :executable?
  end
end
