# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class L8k < Formula
  desc "CLI for deploying NVIDIA cloud-native networking on Kubernetes"
  homepage "https://github.com/nvidia/k8s-launch-kit"
  version "26.10.0-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_darwin_amd64.tar.gz"
      sha256 "d3177d9dc2da09ffa277e96f96c80f8d6e5198350e67c3ccd50646594662d364"

      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_darwin_arm64.tar.gz"
      sha256 "328b6776474063865a4756a6969af7fd0418649d96d17dd8e282a0e2c2bd4d83"

      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_linux_amd64.tar.gz"
      sha256 "cd3e3f247c93262abab4d884f66576932618d659fd52d4fa03b5856373cff5da"
      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.10.0-beta.1/l8k_26.10.0-beta.1_linux_arm64.tar.gz"
      sha256 "9ac5c28db5be35a668d5b9e73c44c4b7167d44557065693efe98fbdd467405bc"
      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k"/"scripts").install "scripts/kubectl-netop_sosreport"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/l8k version")
    assert_predicate share/"l8k"/"scripts"/"kubectl-netop_sosreport", :executable?
  end
end
