# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class L8k < Formula
  desc "CLI for deploying NVIDIA cloud-native networking on Kubernetes"
  homepage "https://github.com/nvidia/k8s-launch-kit"
  version "26.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.4.0/l8k_26.4.0_darwin_amd64.tar.gz"
      sha256 "f3fff015312108507352f61b65d614d554ea529a162eaaa9e5dc4e36e049f982"

      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k").install "presets"
        (share/"l8k").install "l8k-config.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.4.0/l8k_26.4.0_darwin_arm64.tar.gz"
      sha256 "4e446fd9b118b2eb62502f897359db9ae4d7a692ed7fc2dea352036eaf1b8d3e"

      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k").install "presets"
        (share/"l8k").install "l8k-config.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.4.0/l8k_26.4.0_linux_amd64.tar.gz"
      sha256 "1c4a27676b050a147a98dce4ab843537fd6dee8fc61f8ea7148bf3d053b0837c"
      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k").install "presets"
        (share/"l8k").install "l8k-config.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/k8s-launch-kit/releases/download/v26.4.0/l8k_26.4.0_linux_arm64.tar.gz"
      sha256 "b95d822215dc214fd57e169f96718d753373c964adbfce90d56e811d7987083f"
      define_method(:install) do
        bin.install "l8k"
        (share/"l8k").install "profiles"
        (share/"l8k").install "presets"
        (share/"l8k").install "l8k-config.yaml"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/l8k version")
  end
end
