{{if .Profile.Multirail}}
{{- /* Create separate MacVLAN networks for each PF interface */ -}}
{{range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: mellanox.com/v1alpha1
kind: MacvlanNetwork
metadata:
  name: {{$.Macvlan.NetworkName}}-rail-{{$pf.Rail}}{{suffix $.ClusterConfig.Identifier}}
spec:
  networkNamespace: "{{$.PodNamespace}}"
  master: "{{$pf.NetworkInterface}}"
  mode: "bridge"
  mtu: {{$.Sriov.EthernetMtu}}
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "{{$.NvIpam.PoolName}}-rail-{{$pf.Rail}}{{suffix $.ClusterConfig.Identifier}}"
    }
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end}}
{{- end}}
{{- end}}
{{else}}
{{/* Create single shared MacVLAN network for all devices */}}
apiVersion: mellanox.com/v1alpha1
kind: MacvlanNetwork
metadata:
  name: {{.Macvlan.NetworkName}}{{suffix $.ClusterConfig.Identifier}}
spec:
  networkNamespace: "{{$.PodNamespace}}"
  master: "{{(index .ClusterConfig.PFs 0).NetworkInterface}}"
  mode: "bridge"
  mtu: {{.Sriov.EthernetMtu}}
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "{{.NvIpam.PoolName}}{{suffix $.ClusterConfig.Identifier}}"
    }
{{end}}