apiVersion: configuration.net.nvidia.com/v1alpha1
kind: NicConfigurationTemplate
metadata:
  name: spectrum-x-configuration{{suffix .ClusterConfig.Identifier}}
  namespace: "{{.NetworkOperator.Namespace}}"
spec:
  {{- if .ClusterConfig.NodeSelector }}
  nodeSelector:
    {{- range $key, $value := .ClusterConfig.NodeSelector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  nicSelector:
    nicType: "{{.SpectrumX.NicType}}"  # "1023" for ConnectX-8, "1025" for ConnectX-9, "a2dc" for BlueField-3 SuperNIC
  template:
    numVfs: 1
    linkType: Ethernet
    spectrumXOptimized:
      enabled: true
      version: "{{ spectrumXVersionRef .Profile.SpectrumX }}"
      multiplaneMode: "{{.Profile.SpectrumX.MultiplaneMode}}"  # none, swplb, hwplb
      numberOfPlanes: {{.Profile.SpectrumX.NumberOfPlanes}}
      overlay: "{{.SpectrumX.Overlay}}"
