apiVersion: configuration.net.nvidia.com/v1alpha1
kind: NicInterfaceNameTemplate
metadata:
  name: nic-rename-for-spectrum-x
  namespace: {{.NetworkOperator.Namespace}}
spec:
  {{- if .ClusterConfig.NodeSelector }}
  nodeSelector:
    {{- range $key, $value := .ClusterConfig.NodeSelector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  rdmaDevicePrefix: "{{.SpectrumX.RdmaPrefix}}"
  netDevicePrefix: "{{.SpectrumX.NetdevPrefix}}"
  pfsPerNic: {{.Profile.SpectrumX.NumberOfPlanes}}
  railPciAddresses: [{{- $first := true }}{{- range $railIdx, $rail := .ClusterConfig.PFs }}{{- if eq $rail.Traffic "east-west" }}{{- if not $first }}, {{end}}{{- $first = false }}["{{$rail.PciAddress}}"]{{- end }}{{- end }}]
