{{- /* Create separate SriovNetworkNodePolicy per rail using pfNames */ -}}
{{- range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: rail-{{$i}}
  namespace: {{$.NetworkOperator.Namespace}}
spec:
  bridge:
    groupingPolicy: all
    ovs:
      bridge:
        datapathType: netdev
        failMode: secure
      uplink:
        interface:
          type: dpdk
          mtuRequest: 9216
  eSwitchMode: switchdev
  mtu: 9216
  devlinkParams:
  - name: esw_multiport
    value: "true"
    cmode: runtime
    applyOn: PF
  {{- if $.ClusterConfig.NodeSelector }}
  nodeSelector:
    {{- range $key, $value := $.ClusterConfig.NodeSelector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  nicSelector:
    pfNames: [{{- range $planeIdx := untilStep 0 $.Profile.SpectrumX.NumberOfPlanes 1 -}}"{{replaceVars $.SpectrumX.NetdevPrefix $i $planeIdx $i}}"{{if ne $planeIdx (sub $.Profile.SpectrumX.NumberOfPlanes 1)}}, {{end}}{{- end -}}]
  numVfs: 1
  isRdma: true
  linkType: ETH
  resourceName: rail_{{$i}}
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end -}}
{{- end -}}
{{- end -}}
