{{- /* Create separate OVSNetwork per rail */ -}}
{{- range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: sriovnetwork.openshift.io/v1
kind: OVSNetwork
metadata:
  name: rail-{{$i}}
  namespace: {{$.NetworkOperator.Namespace}}
spec:
  resourceName: rail_{{$i}}
  interfaceType: dpdk
  networkNamespace: {{$.PodNamespace}}
  mtu: 9216
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "rail-{{$i}}",
      "poolType": "cidrpool"
    }
  metaPlugins: |
    {
      "type": "rdma"
    },
    {
      "type": "rail"
    }
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end -}}
{{- end -}}
{{- end -}}
