// Copyright 2026 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package config

import (
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	yaml "gopkg.in/yaml.v2"
)

func TestMarshalConfigWithComments(t *testing.T) {
	src := `# top of file banner from source
networkOperator:
  # repository — registry path for component images
  repository: nvcr.io/nvidia/mellanox
  namespace: nvidia-network-operator
nvIpam:
  poolName: nv-ipam-pool
  # IP exclusions doc comment
  reserveFirstIPs: 10
rdmaShared:
  resourceName: rdma_shared_resource # inline note about suffixes
clusterConfig: # inventory section comment
  - identifier: example   # this comment must NOT be carried over
`
	cfg := &LaunchKitConfig{
		NetworkOperator: &NetworkOperatorConfig{
			Repository: "nvcr.io/nvidia/mellanox",
			Namespace:  "nvidia-network-operator",
		},
		NvIpam: &NvIpamConfig{
			PoolName:        "nv-ipam-pool",
			ReserveFirstIPs: 10,
		},
		RdmaShared: &RdmaSharedConfig{ResourceName: "rdma_shared_resource"},
		ClusterConfig: []ClusterConfig{
			{Identifier: "discovered-group"},
		},
	}

	out, err := MarshalConfigWithComments(cfg, []byte(src), "Generated by `l8k discover`.")
	require.NoError(t, err)
	got := string(out)

	t.Run("banner is emitted", func(t *testing.T) {
		assert.Contains(t, got, "# Generated by `l8k discover`.")
	})
	t.Run("head comment on a key is preserved", func(t *testing.T) {
		assert.Contains(t, got, "# repository — registry path for component images")
	})
	t.Run("nested head comment is preserved", func(t *testing.T) {
		assert.Contains(t, got, "# IP exclusions doc comment")
	})
	t.Run("inline value comment is preserved", func(t *testing.T) {
		assert.Contains(t, got, "# inline note about suffixes")
	})
	t.Run("clusterConfig comments are NOT carried over", func(t *testing.T) {
		assert.NotContains(t, got, "must NOT be carried over")
		assert.NotContains(t, got, "inventory section comment")
	})
	t.Run("discovered values win over source values", func(t *testing.T) {
		assert.Contains(t, got, "identifier: discovered-group")
		assert.NotContains(t, got, "identifier: example")
	})
	t.Run("output is valid and reloads to the same values", func(t *testing.T) {
		// Indent is 2 spaces, matching l8k's config style.
		assert.Contains(t, got, "\n  poolName: nv-ipam-pool")
		var reloaded LaunchKitConfig
		require.NoError(t, yaml.Unmarshal(out, &reloaded))
		require.NotNil(t, reloaded.NvIpam)
		assert.Equal(t, 10, reloaded.NvIpam.ReserveFirstIPs)
		require.Len(t, reloaded.ClusterConfig, 1)
		assert.Equal(t, "discovered-group", reloaded.ClusterConfig[0].Identifier)
	})

	t.Run("empty source still emits banner and marshals", func(t *testing.T) {
		out, err := MarshalConfigWithComments(cfg, nil, "banner only")
		require.NoError(t, err)
		assert.Contains(t, string(out), "# banner only")
		assert.Contains(t, string(out), "poolName: nv-ipam-pool")
	})

	t.Run("in-place write-back preserves clusterConfig comments", func(t *testing.T) {
		out, err := MarshalConfigPreservingComments(cfg, []byte(src), "")
		require.NoError(t, err)
		assert.Contains(t, string(out), "# top of file banner from source")
		assert.Contains(t, string(out), "# inventory section comment")
	})
}

// TestMarshalConfigWithComments_RealExampleConfig runs the helper against the
// repo's actual cluster-config.yaml so the round-trip is exercised on the real
// annotated file (best-effort: skipped if the file isn't reachable from the
// test CWD).
func TestMarshalConfigWithComments_RealExampleConfig(t *testing.T) {
	srcBytes, err := os.ReadFile("../../cluster-config.yaml")
	if err != nil {
		t.Skipf("repo cluster-config.yaml not reachable: %v", err)
	}
	var cfg LaunchKitConfig
	require.NoError(t, yaml.Unmarshal(srcBytes, &cfg))
	// Simulate discovery replacing clusterConfig.
	cfg.ClusterConfig = []ClusterConfig{{Identifier: "discovered"}}

	out, err := MarshalConfigWithComments(&cfg, srcBytes, "Generated by `l8k discover`.")
	require.NoError(t, err)
	got := string(out)

	assert.Contains(t, got, "# Generated by `l8k discover`.")

	// Rather than couple the test to specific docstring wording, extract the
	// source's own full-line comments (above the regenerated clusterConfig
	// section) and assert the bulk of them survived the round-trip. This tracks
	// the config file automatically if comments are reworded.
	srcComments := fullLineCommentsBeforeClusterConfig(srcBytes)
	require.NotEmpty(t, srcComments, "the example config should carry documentation comments")
	preserved := 0
	for _, c := range srcComments {
		if strings.Contains(got, c) {
			preserved++
		}
	}
	assert.Greaterf(t, preserved, len(srcComments)/2,
		"most source comments should survive (%d/%d)", preserved, len(srcComments))

	// Output must still parse back into the config struct.
	var reloaded LaunchKitConfig
	require.NoError(t, yaml.Unmarshal(out, &reloaded))
	require.Len(t, reloaded.ClusterConfig, 1)
	assert.Equal(t, "discovered", reloaded.ClusterConfig[0].Identifier)
}

// fullLineCommentsBeforeClusterConfig returns the trimmed full-line `# ...`
// comments that appear before the top-level clusterConfig: key (which discovery
// regenerates, so its comments are intentionally dropped).
func fullLineCommentsBeforeClusterConfig(src []byte) []string {
	var out []string
	for _, line := range strings.Split(string(src), "\n") {
		trimmed := strings.TrimSpace(line)
		if line == "clusterConfig:" { // top-level key (no indentation)
			break
		}
		if strings.HasPrefix(trimmed, "#") {
			out = append(out, trimmed)
		}
	}
	return out
}

func TestMarshalConfigWithComments_NoComments(t *testing.T) {
	cfg := &LaunchKitConfig{
		NetworkOperator: &NetworkOperatorConfig{Namespace: "ns"},
	}
	out, err := MarshalConfigWithComments(cfg, nil, "")
	require.NoError(t, err)
	assert.False(t, strings.HasPrefix(string(out), "#"), "no banner, no leading comment")
	assert.Contains(t, string(out), "namespace: ns")
}

func TestMarshalConfigWithCommentsPreservesExplicitEmptyCollections(t *testing.T) {
	cfg := &LaunchKitConfig{
		NetworkNamespaces: []string{},
		Validation: &ValidationConfig{
			Checks: []string{},
		},
	}
	out, err := MarshalConfigWithComments(cfg, nil, "")
	require.NoError(t, err)
	assert.Contains(t, string(out), "networkNamespaces: []")
	assert.Contains(t, string(out), "checks: []")

	input, err := DecodeInput(out, "round-trip.yaml")
	require.NoError(t, err)
	assert.True(t, input.Present.Has("networkNamespaces"))
	assert.True(t, input.Present.Has("validation.checks"))
	assert.Empty(t, input.Config.NetworkNamespaces)
	assert.Empty(t, input.Config.Validation.Checks)
}

func TestPatchConfigYAMLUpdatesAliasedMappingIndependently(t *testing.T) {
	source := []byte(`shared: &shared
  namespace: original # namespace note
  imagePullSecrets: [secret]
networkOperator:
  <<: *shared
  selectedRelease: ""
docaDriver:
  enable: &disabled false
validation:
  connectivity: *disabled
`)
	input, err := DecodeInput(source, "aliases.yaml")
	require.NoError(t, err)
	input.Config.NetworkOperator.Namespace = "changed"
	input.Config.DOCADriver.Enable = true
	out, err := PatchConfigYAML(source, input.Config,
		[]string{"networkOperator.namespace", "docaDriver.enable"}, "")
	require.NoError(t, err)
	after, err := DecodeInput(out, "patched.yaml")
	require.NoError(t, err)
	assert.Equal(t, "changed", after.Config.NetworkOperator.Namespace)
	assert.Equal(t, []string{"secret"}, after.Config.NetworkOperator.ImagePullSecrets)
	assert.True(t, after.Config.DOCADriver.Enable)
	require.NotNil(t, after.Config.Validation.Connectivity)
	assert.False(t, *after.Config.Validation.Connectivity, "an alias must not follow the edited anchor")
	assert.True(t, after.Present.Has("networkOperator.selectedRelease"))
	assert.Contains(t, string(out), "namespace: original")
	assert.Contains(t, string(out), "# namespace note")
}

func TestPatchConfigYAMLWritesExplicitZeroOverrides(t *testing.T) {
	input, err := DecodeInput([]byte("profile: null\n"), "empty.yaml")
	require.NoError(t, err)
	input.Config.Profile = &Profile{Multirail: false}
	input.Config.NetworkOperator = &NetworkOperatorConfig{SelectedRelease: ""}
	out, err := PatchConfigYAML(input.SourceYAML, input.Config,
		[]string{"profile.multirail", "networkOperator.selectedRelease"}, "")
	require.NoError(t, err)
	after, err := DecodeInput(out, "patched.yaml")
	require.NoError(t, err)
	assert.True(t, after.Present.Has("profile.multirail"))
	assert.True(t, after.Present.Has("networkOperator.selectedRelease"))
	assert.False(t, after.Present.Has("profile.fabric"))
	assert.False(t, after.Config.Profile.Multirail)
}

func TestMarshalConfigWithCommentsPreservesExplicitScalarZeros(t *testing.T) {
	source := []byte(`networkOperator:
  selectedRelease: "" # custom coordinates
nvIpam:
  offset: 0 # start at zero
`)
	input, err := DecodeInput(source, "source.yaml")
	require.NoError(t, err)
	out, err := MarshalConfigWithComments(input.Config, source, "")
	require.NoError(t, err)
	reloaded, err := DecodeInput(out, "saved.yaml")
	require.NoError(t, err)
	assert.True(t, reloaded.Present.Has("networkOperator.selectedRelease"))
	assert.True(t, reloaded.Present.Has("nvIpam.offset"))
	assert.Empty(t, reloaded.Config.NetworkOperator.SelectedRelease)
	assert.Zero(t, reloaded.Config.NvIpam.Offset)
	assert.Contains(t, string(out), "# custom coordinates")
	assert.Contains(t, string(out), "# start at zero")
}
