// Copyright 2026 NVIDIA CORPORATION & AFFILIATES.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by go generate; DO NOT EDIT.

package config

var defaultConfigYAML = []byte(
	"# Generated by `l8k discover`. Field documentation below is carried over\n" +
	"# from the reference config; edit values as needed, then run `l8k generate`.\n" +
	"\n" +
	"# Select Kubernetes or OpenShift operator integration. Defaults to k8s.\n" +
	"flavor: k8s\n" +
	"\n" +
	"networkOperator:\n" +
	"  # selectedRelease pins the Network Operator release line (MAJOR.MINOR).\n" +
	"  # Equivalent to passing --network-operator-release on the CLI. When set,\n" +
	"  # version/componentVersion/repository/operatorRepository/helmRepoURL (below)\n" +
	"  # and docaDriver.version are populated from the embedded catalog;\n" +
	"  # explicit values here are overridden.\n" +
	"  # Supported: 26.1, 26.4, 26.7. Leave empty to use the explicit values\n" +
	"  # below as-is.\n" +
	"  # selectedRelease: \"26.7\"\n" +
	"  version: v26.7.0\n" +
	"  componentVersion: network-operator-v26.7.0\n" +
	"  selectedRelease: \"26.7\"\n" +
	"  skipHelmChart: false\n" +
	"  # repository — registry path for COMPONENT images managed by the operator\n" +
	"  # (ofedDriver, nvIpam, multus, device plugins, …). Rendered into\n" +
	"  # NicClusterPolicy / NicNodePolicy.\n" +
	"  repository: nvcr.io/nvidia/mellanox\n" +
	"  # operatorRepository — registry path for the network-operator BINARY\n" +
	"  # image itself. Distinct from `repository` because stable releases ship\n" +
	"  # the operator at `nvcr.io/nvidia/cloud-native` while components live at\n" +
	"  # `nvcr.io/nvidia/mellanox`. Rendered into the helm chart's\n" +
	"  # `operator.repository` value.\n" +
	"  operatorRepository: nvcr.io/nvidia/cloud-native\n" +
	"  namespace: nvidia-network-operator\n" +
	"  # imagePullSecrets:\n" +
	"  #   - my-registry-secret\n" +
	"\n" +
	"  # helmRepoURL — Helm chart repository URL the `l8k deploy` Phase 0 fetches\n" +
	"  # the network-operator chart from. Stable releases publish under\n" +
	"  # `helm.ngc.nvidia.com/nvidia`; staging under `helm.ngc.nvidia.com/nvstaging/mellanox`.\n" +
	"  helmRepoURL: https://helm.ngc.nvidia.com/nvidia\n" +
	"# workload:\n" +
	"#   manifest: /path/to/my-deployment.yaml  # Custom workload manifest (replaces default example DaemonSet)\n" +
	"networkNamespaces: [default]\n" +
	"validation:\n" +
	"  connectivity: true\n" +
	"  mode: strict\n" +
	"  checks: [icmp, rping, ib_write_bw]\n" +
	"  rdma:\n" +
	"    rpingIterations: 5\n" +
	"    ibWriteSize: 65536\n" +
	"    ibWriteMinBandwidthGbps: 100\n" +
	"  gpuDirect:\n" +
	"    enabled: false\n" +
	"    gpuResourceType: nvidia.com/gpu\n" +
	"docaDriver:\n" +
	"  enable: true\n" +
	"  version: doca3.5.0-26.07-0.7.7.0-0\n" +
	"  unloadStorageModules: true\n" +
	"  enableNFSRDMA: false\n" +
	"  unloadThirdPartyRDMAModules: true\n" +
	"  skipPreflightChecks: false\n" +
	"  # Advanced users only: literal environment variables forwarded to MOFED.\n" +
	"  # env:\n" +
	"  #   - name: THIRD_PARTY_RDMA_MODULES\n" +
	"  #     value: \"nvidia_peermem\"\n" +
	"maintenance:\n" +
	"  # OpenShift Maintenance Operator namespace. Package installation is external.\n" +
	"  # operatorNamespace: nvidia-maintenance-operator\n" +
	"  # Global concurrency; positive integer or 1%-100%.\n" +
	"  maxParallelOperations: 4\n" +
	"  # Global or legacy SR-IOV limit; non-negative integer or 1%-100%.\n" +
	"  maxUnavailable: 4\n" +
	"  # Ready-request cleanup delay in seconds; non-negative.\n" +
	"  maxNodeMaintenanceTimeSeconds: 3600\n" +
	"  # Legacy OFED concurrency; non-negative, 0 is unlimited.\n" +
	"  maxParallelUpgrades: 4\n" +
	"nvIpam:\n" +
	"  poolName: nv-ipam-pool\n" +
	"  perNodeBlockSize: 10\n" +
	"  # --- Option 1: Auto-generate subnets (used when subnets list is empty) ---\n" +
	"  # Each group gets its own unique subnet slice; gateway = network address + 1.\n" +
	"  startingSubnet: 192.168.0.0\n" +
	"  mask: 22\n" +
	"  offset: 1\n" +
	"  # IP exclusions (optional). reserveFirstIPs/reserveLastIPs apply to EVERY\n" +
	"  # subnet, including each auto-generated per-rail subnet — they reserve the\n" +
	"  # first N and last N host addresses (gateway is covered by the low block).\n" +
	"  # reserveFirstIPs: 10   # e.g. .0–.9 on a /24\n" +
	"  # reserveLastIPs: 6     # e.g. .250–.255 on a /24\n" +
	"  #\n" +
	"  # --- Option 2: Manually list subnets (takes precedence if non-empty) ---\n" +
	"  # subnets:\n" +
	"  # - subnet: 192.168.2.0/24\n" +
	"  #   gateway: 192.168.2.1\n" +
	"  #   # explicit per-subnet exclusions are merged on top of the reserve pattern:\n" +
	"  #   exclusions:\n" +
	"  #   - {startIP: 192.168.2.2, endIP: 192.168.2.3}\n" +
	"  # - subnet: 192.168.3.0/24\n" +
	"  #   gateway: 192.168.3.1\n" +
	"  # - subnet: 192.168.4.0/24\n" +
	"  #   gateway: 192.168.4.1\n" +
	"  # - subnet: 192.168.5.0/24\n" +
	"  #   gateway: 192.168.5.1\n" +
	"  # - subnet: 192.168.6.0/24\n" +
	"  #   gateway: 192.168.6.1\n" +
	"  # - subnet: 192.168.7.0/24\n" +
	"  #   gateway: 192.168.7.1\n" +
	"  # - subnet: 192.168.8.0/24\n" +
	"  #   gateway: 192.168.8.1\n" +
	"  # - subnet: 192.168.9.0/24\n" +
	"  #   gateway: 192.168.9.1\n" +
	"  # - subnet: 192.168.10.0/24\n" +
	"  #   gateway: 192.168.10.1\n" +
	"sriov:\n" +
	"  # OpenShift SR-IOV Operator namespace. Package installation is external.\n" +
	"  # operatorNamespace: openshift-sriov-network-operator\n" +
	"  ethernetMtu: 9000\n" +
	"  infinibandMtu: 4000\n" +
	"  numVfs: 8\n" +
	"  priority: 90\n" +
	"  resourceName: sriov_resource\n" +
	"  networkName: sriov-network\n" +
	"# OpenShift Node Feature Discovery configuration object. Its installation is external.\n" +
	"# nfd:\n" +
	"#   operatorNamespace: openshift-nfd\n" +
	"#   configurationName: nfd-instance\n" +
	"hostdev:\n" +
	"  resourceName: hostdev_resource\n" +
	"  networkName: hostdev-network\n" +
	"rdmaShared:\n" +
	"  resourceName: rdma_shared_resource # with multiple pools, _rail_0, _rail_1, etc. suffixes are added to the resource name\n" +
	"  hcaMax: 63\n" +
	"ipoib:\n" +
	"  networkName: ipoib-network # with multiple networks, -rail-0, -rail-1, etc. suffixes are added to the network name\n" +
	"macvlan:\n" +
	"  networkName: macvlan-network # with multiple networks, -rail-0, -rail-1, etc. suffixes are added to the network name\n" +
	"spectrumX:\n" +
	"  overlay: none\n" +
	"  singlePlane:\n" +
	"    netdevPrefix: \"eth_r%rail_id%\"\n" +
	"    rdmaPrefix: \"roce_r%rail_id%\"\n" +
	"  hwplb:\n" +
	"    netdevPrefix: \"eth_r%rail_id%_p%plane_id%\"\n" +
	"    rdmaPrefix: \"roce_r%rail_id%\"\n" +
	"  swplb:\n" +
	"    netdevPrefix: \"eth_r%rail_id%_p%plane_id%\"\n" +
	"    rdmaPrefix: \"roce_r%rail_id%_p%plane_id%\"\n" +
	"nicConfigurationOperator:\n" +
	"  deployNicInterfaceNameTemplate: true\n" +
	"  rdmaPrefix: rdma_r%rail_id%\n" +
	"  netdevPrefix: eth_r%rail_id%\n" +
	"podNamespace: default\n" +
	"clusterConfig:\n" +
	"  - identifier: \"\"\n" +
	"    machineType: X9DRFF-i/7(T)+\n" +
	"    linkType: Ethernet\n" +
	"    capabilities:\n" +
	"      nodes:\n" +
	"        sriov: true\n" +
	"        rdma: true\n" +
	"        ib: true\n" +
	"    pfs:\n" +
	"      - deviceID: 101d\n" +
	"        rdmaDevice: mlx5_0\n" +
	"        pciAddress: \"0000:03:00.0\"\n" +
	"        networkInterface: enp3s0f0np0\n" +
	"        traffic: east-west\n" +
	"        rail: 0\n" +
	"        psid: mt_0000000436\n" +
	"        partNumber: MCX623106AC-CDAT\n" +
	"        model: ConnectX-6 Dx EN adapter card\n" +
	"        numaNode: 0\n" +
	"      - deviceID: \"1015\"\n" +
	"        rdmaDevice: mlx5_2\n" +
	"        pciAddress: 0000:81:00.0\n" +
	"        networkInterface: enp129s0np0\n" +
	"        traffic: east-west\n" +
	"        rail: 1\n" +
	"        psid: mt_2430110032\n" +
	"        partNumber: MCX4131A-GCAT\n" +
	"        model: CX4131A - ConnectX-4 LX QSFP28\n" +
	"        numaNode: 1\n" +
	"    workerNodes:\n" +
	"      - cloud-dev-40\n" +
	"      - cloud-dev-41\n" +
	"    nodeSelector:\n" +
	"      feature.node.kubernetes.io/pci-15b3.present: \"true\"\n" +
	"",
)
